### ISSUE TITLE
sanitize content of posts

### ISSUE THREAD

**Issue by andy128k** [andy128k/reader#11]

**Comment by andy128k** [comment]
http://minus.com/mHb4KEdTA а поста то выше нету

**Comment by andy128k** [comment]
Я подписался на эту же рассылку. Нашёл этот пост. Ошибка не воспроизводися. Проверял в FF10 и Chrome17

**Comment by alder** [comment]
Ошибка была в том случае, когда этот пост был первым в режиме View unread only.

**Comment by andy128k** [comment]
Именно так и  проверял

<img src="http://img593.imageshack.us/img593/9665/screenshot20120214at148.png">

**Comment by alder** [comment]
Спишем на глюк браузера, возможно кэш. Если повторится - переоткрою.
