### ISSUE TITLE
Settings dropdown has no icon

### ISSUE THREAD

**Issue by Vadhrnt** [andy128k/reader#33]
See the screenshot.
<img src="http://i.imgur.com/JKD6s.png">

The settings dropdown icon is not shown properly on some systems.

Caught it on WinXP Home SP3, Firefox 12.0 beta. (Icon is not shown in Chrome 18.0.1025.162 as well.)

But it's shown OK in all browsers on Windows 7, so the problem is about Win XP probably.

**Comment by andy128k** [comment]
В XP нету нужного шрифта. Я специально не заморачивался.

**Comment by Vadhrnt** [comment]
Я так и понял на самом деле. Просто на всякий случай написал, вдруг просто никто не знает.
