### ISSUE TITLE
True Friends

### ISSUE THREAD

**Issue by dra1n** [andy128k/reader#36]
There is an issue with unread counter

![Screen Shot 2012-12-18 at 10 03 00 AM](https://f.cloud.github.com/assets/309593/18878/a0018716-48e9-11e2-9b16-09fb363114a4.png)

**Comment by alder** [comment]
This issue is also happens for me:
![Screenshot_013](https://f.cloud.github.com/assets/199887/72757/e604ecd6-6021-11e2-8cc4-f0fc0ff2ef60.png)

**Comment by MsSterh** [comment]
This feature shows who are really your friend!
