### ISSUE TITLE
Internal Server Error when try to mark all as read

### ISSUE THREAD

**Issue by alder** [andy128k/reader#38]
1. View items from category
2. Press Mark as read.

Details:
Internal Server Error
An error occured while processing your /ajax/all-read/ request.
Error Message

Database error 42703: column "source" does not exist
Query: UPDATE feeds_post SET read_by_owner = true WHERE ((user_id = slot_value(source, user_id)) and (not read_by_owner) and (feed_id IN (119)) and (user_id = 2))

Backtrace

0: (SB-DEBUG::MAP-BACKTRACE
    #<CLOSURE (LAMBDA # :IN BACKTRACE) {1008606E2B}>
    :START
    0
    :COUNT
    4611686018427387903)
1: (BACKTRACE 4611686018427387903 #<SB-IMPL::STRING-OUTPUT-STREAM {1008606D33}>)
2: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM
    #<SB-IMPL::STRING-OUTPUT-STREAM {1008606D33}>)
3: (HUNCHENTOOT::GET-BACKTRACE)
4: ((FLET #:LAMBDA918 :IN HUNCHENTOOT:HANDLE-REQUEST)
    #<CL-POSTGRES-ERROR:SYNTAX-ERROR-OR-ACCESS-VIOLATION {10085DFEE3}>)
5: (SIGNAL #<CL-POSTGRES-ERROR:SYNTAX-ERROR-OR-ACCESS-VIOLATION {10085DFEE3}>)
6: (ERROR
    CL-POSTGRES-ERROR:SYNTAX-ERROR-OR-ACCESS-VIOLATION
    :CODE
    "42703"
    :MESSAGE
    "column \"source\" does not exist"
    :DETAIL
    NIL
    :POSITION
    NIL)
7: (CL-POSTGRES::GET-ERROR
    #<SB-SYS:FD-STREAM for "socket 127.0.0.1:48036, peer: 127.0.0.1:5432"
      {10093F7363}>)
8: (CL-POSTGRES::SEND-QUERY
    #<unavailable argument>
    #<unavailable argument>
    #<unavailable argument>)
9: ((LABELS #:G310 :IN CL-POSTGRES:EXEC-QUERY))
10: ((SB-PCL::FAST-METHOD READER::SOURCE-MARK-AS-READ (READER::POST-OWNER))
     #<unavailable argument>
     #<unavailable argument>
     #<READER::CATEGORY-SOURCE {10085BED73}>)
11: ((LABELS #:|/ajax/all-read/1646| :IN "/home/reader/quicklisp/local-projects/cl-reader/src/views.lisp"))
12: ((SB-PCL::FAST-METHOD HUNCHENTOOT:HANDLE-REQUEST
      (HUNCHENTOOT:ACCEPTOR HUNCHENTOOT:REQUEST))
     #<unavailable argument>
     #<unavailable argument>
     #<HUNCHENTOOT:EASY-ACCEPTOR (host *, port 4242)>
     #<HUNCHENTOOT:REQUEST {100845F3B3}>)
13: ((SB-PCL::FAST-METHOD HUNCHENTOOT:PROCESS-REQUEST (T))
     #<unavailable argument>
     #<unavailable argument>
     #<HUNCHENTOOT:REQUEST {100845F3B3}>)
14: (HUNCHENTOOT::DO-WITH-ACCEPTOR-REQUEST-COUNT-INCREMENTED
     #<HUNCHENTOOT:EASY-ACCEPTOR (host *, port 4242)>
     #<CLOSURE (LAMBDA # :IN HUNCHENTOOT:PROCESS-CONNECTION) {100845F36B}>)
15: ((SB-PCL::FAST-METHOD HUNCHENTOOT:PROCESS-CONNECTION
      (HUNCHENTOOT:ACCEPTOR T))
     #<unavailable argument>
     #<unavailable argument>
     #<HUNCHENTOOT:EASY-ACCEPTOR (host *, port 4242)>
     #<USOCKET:STREAM-USOCKET {10083FE253}>)
16: ((SB-PCL::FAST-METHOD HUNCHENTOOT:PROCESS-CONNECTION :AROUND
      (HUNCHENTOOT:ACCEPTOR T))
     #<unavailable argument>
     #S(SB-PCL::FAST-METHOD-CALL
        :FUNCTION #<FUNCTION #>
        :PV NIL
        :NEXT-METHOD-CALL NIL
        :ARG-INFO (2))
     #<HUNCHENTOOT:EASY-ACCEPTOR (host *, port 4242)>
     #<USOCKET:STREAM-USOCKET {10083FE253}>)
17: ((FLET HUNCHENTOOT::PROCESS-CONNECTION% :IN HUNCHENTOOT::HANDLE-INCOMING-CONNECTION%)
     #<HUNCHENTOOT:EASY-ACCEPTOR (host *, port 4242)>
     #<USOCKET:STREAM-USOCKET {10083FE253}>)
18: ((LAMBDA () :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
19: ((FLET #:WITHOUT-INTERRUPTS-BODY-238738 :IN SB-THREAD:MAKE-THREAD))
20: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD:MAKE-THREAD))
21: ((FLET #:WITHOUT-INTERRUPTS-BODY-89211 :IN SB-THREAD::CALL-WITH-MUTEX))
22: (SB-THREAD::CALL-WITH-MUTEX
     #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD:MAKE-THREAD)
       {7FFFF506EC1B}>
     #<SB-THREAD:MUTEX "thread result lock"
         owner: #<SB-THREAD:THREAD "hunchentoot-worker-127.0.0.1:38863" RUNNING
                   {10084079A3}>>
     #<SB-THREAD:THREAD "hunchentoot-worker-127.0.0.1:38863" RUNNING
        {10084079A3}>
     T)
23: (SB-THREAD::INITIAL-THREAD-FUNCTION)
24: ("foreign function: call_into_lisp")
25: ("foreign function: new_thread_trampoline")

**Comment by andy128k** [comment]
Мерси
Исправил

2012/12/20 Aleksey Derkach notifications@github.com
