### ISSUE TITLE
Acute accent displayed as non-UTF8 symbol in articles titles

### ISSUE THREAD

**Issue by alder** [andy128k/reader#50]
Expected result:  Reinout van Rees: Pygrunn: Python, WebRTC and You - Saúl Ibarra Corretgé
Actual result: Reinout van Rees: Pygrunn: Python, WebRTC and You - Sa��l Ibarra Corretg��

**Comment by andy128k** [comment]
http://planetpython.org/rss20.xml

**Comment by andy128k** [comment]
То же что и в #51
