### ISSUE TITLE
Invalid encoding for arabic language

### ISSUE THREAD

**Issue by alder** [andy128k/reader#51]
RSS: http://planetpython.org/rss20.xml
Original post: http://pyarab.com/2015/07/using-the-platform-module-in-python-2.html
Screenshot:
![capturfiles-201507188_170779](https://cloud.githubusercontent.com/assets/199887/8549099/809fdb72-24d1-11e5-82c5-93d9343a8021.png)

**Comment by andy128k** [comment]
Сносило крышу детектору кодировки. Я его выключил.
